@wb_sklad = /api/v1/acceptance/coefficients

###
// запрос данных на загрузку ассортимента
// ?isLoadingImages=false загрузка без картинок
GET http://{{url_wb}}{{wb_sklad}}
?warehouseIDs=131643 
Authorization: {{wb_token}}

###
GET http://{{url_wb}}{{wb_sklad}}
Authorization: {{wb_token}}




